version: "3.7"
services:

  auth:
    image: tomerfries-auth
    env_file:
      - env_vars.txt

  web:
    image: tomerfries-web
    env_file:
      - env_vars.txt

  api:
    image: tomerfries-api
    env_file:
      - env_vars.txt

  nginx:
    image: tomerfries-nginx
    ports:
      - "5443:443"

  sql:
    image: tomerfries-sql
    volumes:
      - d:\TomerFries\App\sql\store:/var/opt/mssql/data
    ports:
      - "8633:1433"
