version: "3.7"
services:

  auth:
    image: armadillo.azurecr.io/tomerfries/auth

  web:
    image: armadillo.azurecr.io/tomerfries/web

  api:
    image: armadillo.azurecr.io/tomerfries/api

  nginx:
    image: armadillo.azurecr.io/tomerfries/nginx
    ports:
      - "80:80"
      - "443:443"
